// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Simple_FrontEnd.Models
{
    public partial class Countries
    {
        public Countries()
        {
            Participants = new HashSet<Participants>();
        }

        public int CountryId { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Participants> Participants { get; set; }
    }
}