// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Simple_FrontEnd.Models
{
    public partial class IdentificationType
    {
        public IdentificationType()
        {
            Custumers = new HashSet<Custumers>();
        }

        public int IdentificationId { get; set; }
        public string IdentificationType1 { get; set; }
        public string IdentificationFormat { get; set; }

        public virtual ICollection<Custumers> Custumers { get; set; }
    }
}