// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Simple_FrontEnd.Models
{
    public partial class ParticipantsType
    {
        public ParticipantsType()
        {
            Participants = new HashSet<Participants>();
        }

        public int Ptype_Id { get; set; }
        public string ShortName { get; set; }
        public string Description { get; set; }
        public bool IsDeleting { get; set; }

        public virtual ICollection<Participants> Participants { get; set; }
    }
}