// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Simple_FrontEnd.Models
{
    public partial class PaymentType
    {
        public int Payment_Id { get; set; }
        public string Description { get; set; }
        public bool IsDeleting { get; set; }
    }
}