// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Simple_FrontEnd.Models
{
    public partial class PendingTransactions
    {
        public long TrnsId { get; set; }
        public int FromPartdId { get; set; }
        public int ToPartId { get; set; }
        public decimal Amount { get; set; }
        public int NotificationId { get; set; }
        /// <summary>
        /// 0= pendiente,1 enviado,2 error.
        /// </summary>
        public int CustomerNotificationStatus { get; set; }
        public long CustomerId { get; set; }
        /// <summary>
        /// 0= pendiente,1 enviado,2 error.
        /// </summary>
        public int PayStatus { get; set; }

        public virtual Custumers Customer { get; set; }
        public virtual Participants FromPartd { get; set; }
        public virtual NotificationType Notification { get; set; }
        public virtual Participants ToPart { get; set; }
    }
}