// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Simple_FrontEnd.Models
{
    public partial class Users
    {
        public int User_Id { get; set; }
        public int Part_Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public int Utype_Id { get; set; }
        public string Password { get; set; }
        public bool Enabled { get; set; }
        public bool IsDeleting { get; set; }

        public virtual Participants Part { get; set; }
        public virtual UsersType Utype { get; set; }
    }
}