// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Simple_BackEndAPI.Models
{
    public partial class Customer
    {
        public long Cliente_Id { get; set; }
        public int Part_Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastNames { get; set; }
        public int Identification_Id { get; set; }
        public string Identification_Number { get; set; }
        public decimal CountryCode { get; set; }
        public decimal PhoneNumber { get; set; }
        public string Email { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime UpdateDate { get; set; }
        public int Last_User_Id_Change { get; set; }
    }
}