// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Simple_BackEndAPI.Models
{
    public partial class Identification_Type
    {
        public int Identification_Id { get; set; }
        public string Identification_type1 { get; set; }
        public string Identification_Format { get; set; }
    }
}