// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Simple_BackEndAPI.Models
{
    public partial class Log
    {
        public long Log_Id { get; set; }
        public DateTime Date_Log { get; set; }
        public string Description { get; set; }
    }
}