// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Simple_BackEndAPI.Models
{
    public partial class Notification_Type
    {
        public int Notification_Id { get; set; }
        public string Description { get; set; }
    }
}