// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Simple_BackEndAPI.Models
{
    public partial class Participant
    {
        public int Part_Id { get; set; }
        public int Ptype_Id { get; set; }
        public int Country_Id { get; set; }
        public string Description { get; set; }
        public bool Enabled { get; set; }
    }
}