// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Simple_BackEndAPI.Models
{
    public partial class Pending_Transaction
    {
        public long Trns_Id { get; set; }
        public int From_Partd_Id { get; set; }
        public int To_Part_Id { get; set; }
        public decimal Amount { get; set; }
        public int Notification_Id { get; set; }
        /// <summary>
        /// 0= pendiente,1 enviado,2 error.
        /// </summary>
        public int Customer_Notification_Status { get; set; }
        public long Customer_Id { get; set; }
        /// <summary>
        /// 0= pendiente,1 enviado,2 error.
        /// </summary>
        public int Pay_Status { get; set; }

    }
}